/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 6;
  /** RegularExpression Id. */
  int ACHAVES = 7;
  /** RegularExpression Id. */
  int FCHAVES = 8;
  /** RegularExpression Id. */
  int AParen = 9;
  /** RegularExpression Id. */
  int FParen = 10;
  /** RegularExpression Id. */
  int VOID = 11;
  /** RegularExpression Id. */
  int FLOAT = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int BOOL = 14;
  /** RegularExpression Id. */
  int MULT = 15;
  /** RegularExpression Id. */
  int SEMICOLON = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int let = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int DEF = 20;
  /** RegularExpression Id. */
  int printio = 21;
  /** RegularExpression Id. */
  int readio = 22;
  /** RegularExpression Id. */
  int ATRIB = 23;
  /** RegularExpression Id. */
  int SUM = 24;
  /** RegularExpression Id. */
  int LESS = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int NUM = 27;
  /** RegularExpression Id. */
  int ID = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\"\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"void\"",
    "\"flot\"",
    "\"int\"",
    "\"bool\"",
    "\"*\"",
    "\";\"",
    "\",\"",
    "\"let\"",
    "\"return\"",
    "\"def\"",
    "\"printIO\"",
    "\"readIO\"",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "<NUM>",
    "<ID>",
  };

}
